// Mock categories
export const mockCategories = [
  { id: '1', name: 'Property Management', slug: 'property-management', description: 'Apartment complexes and property managers', icon: 'building', created_at: '', complaint_count: 8934 },
  { id: '2', name: 'Landlords', slug: 'landlords', description: 'Individual landlords and rental owners', icon: 'home', created_at: '', complaint_count: 3421 },
  { id: '3', name: 'HOA', slug: 'hoa', description: 'Homeowner associations', icon: 'users', created_at: '', complaint_count: 2156 },
  { id: '4', name: 'Real Estate', slug: 'real-estate', description: 'Real estate agents and brokers', icon: 'map', created_at: '', complaint_count: 1876 },
  { id: '5', name: 'Contractors', slug: 'contractors', description: 'General contractors, electricians, plumbers', icon: 'hammer', created_at: '', complaint_count: 4532 },
  { id: '6', name: 'Moving Companies', slug: 'moving-companies', description: 'Moving and relocation services', icon: 'truck', created_at: '', complaint_count: 2341 },
  { id: '7', name: 'Non-Payment', slug: 'non-payment', description: 'Businesses refusing to pay for services', icon: 'alert-circle', created_at: '', complaint_count: 5678 },
  { id: '8', name: 'Electrical Issues', slug: 'electrical-issues', description: 'Electrical hazards and code violations', icon: 'zap', created_at: '', complaint_count: 1234 },
  { id: '9', name: 'Plumbing Issues', slug: 'plumbing-issues', description: 'Plumbing failures and water damage', icon: 'droplet', created_at: '', complaint_count: 1567 },
  { id: '10', name: 'Safety Hazards', slug: 'safety-hazards', description: 'Fire safety, structural issues, mold', icon: 'shield-alert', created_at: '', complaint_count: 2890 },
]

// Mock states
export const mockStates = [
  { id: '1', name: 'Alabama', abbreviation: 'AL', complaint_count: 7837, created_at: '' },
  { id: '2', name: 'Arizona', abbreviation: 'AZ', complaint_count: 612, created_at: '' },
  { id: '3', name: 'California', abbreviation: 'CA', complaint_count: 2847, created_at: '' },
  { id: '4', name: 'Florida', abbreviation: 'FL', complaint_count: 1892, created_at: '' },
  { id: '5', name: 'Georgia', abbreviation: 'GA', complaint_count: 743, created_at: '' },
  { id: '6', name: 'Illinois', abbreviation: 'IL', complaint_count: 987, created_at: '' },
  { id: '7', name: 'New York', abbreviation: 'NY', complaint_count: 1654, created_at: '' },
  { id: '8', name: 'Texas', abbreviation: 'TX', complaint_count: 2134, created_at: '' },
]

// Mock users with real avatars
export const mockUsers = [
  {
    id: "user-1",
    username: "sarah_m",
    display_name: "Sarah Mitchell",
    avatar_url: "/avatars/user-1.jpg",
    reputation: 2847,
    is_verified: true,
  },
  {
    id: "user-2",
    username: "marcus_j",
    display_name: "Marcus Johnson",
    avatar_url: "/avatars/user-2.jpg",
    reputation: 1523,
    is_verified: true,
  },
  {
    id: "user-3",
    username: "alex_dev",
    display_name: "Alex Rivera",
    avatar_url: "/avatars/user-3.jpg",
    reputation: 892,
    is_verified: false,
  },
  {
    id: "user-4",
    username: "david_k",
    display_name: "David Kozlov",
    avatar_url: "/avatars/user-4.jpg",
    reputation: 456,
    is_verified: false,
  },
  {
    id: "user-5",
    username: "jaylen_w",
    display_name: "Jaylen Williams",
    avatar_url: "/avatars/user-5.jpg",
    reputation: 3201,
    is_verified: true,
  },
  {
    id: "user-6",
    username: "marco_p",
    display_name: "Marco Perez",
    avatar_url: "/avatars/user-6.jpg",
    reputation: 678,
    is_verified: false,
  },
  {
    id: "user-7",
    username: "mei_chen",
    display_name: "Mei Chen",
    avatar_url: "/avatars/user-7.jpg",
    reputation: 1876,
    is_verified: true,
  },
  {
    id: "user-8",
    username: "emma_g",
    display_name: "Emma Garcia",
    avatar_url: "/avatars/user-8.jpg",
    reputation: 2134,
    is_verified: true,
  },
  {
    id: "user-9",
    username: "fatima_a",
    display_name: "Fatima Al-Hassan",
    avatar_url: "/avatars/user-9.jpg",
    reputation: 945,
    is_verified: false,
  },
  {
    id: "user-10",
    username: "jennifer_l",
    display_name: "Jennifer Lin",
    avatar_url: "/avatars/user-10.jpg",
    reputation: 4102,
    is_verified: true,
  },
];

// Mock complaints for realistic data
export const mockComplaints = [
  {
    id: "complaint-1",
    title: "Greystar Property Management refused to return $2,400 security deposit",
    content: "After living at their property for 3 years with no issues, they claimed 'excessive wear and tear' and kept my entire deposit. The apartment was spotless when I left. I have photos to prove it. They're refusing to provide itemized deductions as required by state law.",
    user: mockUsers[0],
    company_name: "Greystar Property Management",
    company_slug: "greystar-property-management",
    category: "Property Management",
    state: "California",
    city: "Los Angeles",
    severity: 5,
    status: "open",
    upvotes: 847,
    downvotes: 12,
    comment_count: 156,
    view_count: 12453,
    created_at: "2026-03-08T14:32:00Z",
    is_featured: true,
  },
  {
    id: "complaint-2",
    title: "HOA fined me $500 for parking my car in my own driveway",
    content: "Our HOA has gone completely overboard. They fined me for parking my Toyota Camry in my driveway because it was 'not in the garage.' My garage is full of storage because the HOA won't let us have a shed. This is beyond absurd.",
    user: mockUsers[1],
    company_name: "Riverside Heights HOA",
    company_slug: "riverside-heights-hoa",
    category: "HOA",
    state: "Texas",
    city: "Austin",
    severity: 4,
    status: "investigating",
    upvotes: 1203,
    downvotes: 45,
    comment_count: 289,
    view_count: 18762,
    created_at: "2026-03-07T09:15:00Z",
    is_featured: true,
  },
  {
    id: "complaint-3",
    title: "Landlord entered my apartment without notice 4 times this month",
    content: "My landlord keeps entering my unit without the legally required 24-hour notice. He claims he's 'checking the HVAC' but I've caught him going through my kitchen cabinets. I feel completely violated in my own home.",
    user: mockUsers[2],
    company_name: "John Michaels Properties",
    company_slug: "john-michaels-properties",
    category: "Landlords",
    state: "New York",
    city: "Brooklyn",
    severity: 5,
    status: "open",
    upvotes: 567,
    downvotes: 8,
    comment_count: 92,
    view_count: 8934,
    created_at: "2026-03-09T16:45:00Z",
    is_featured: false,
  },
  {
    id: "complaint-4",
    title: "Moving company held my furniture hostage for extra $1,200",
    content: "Two Men and a Truck quoted me $800 for my move. When they arrived at my new place, they demanded an additional $1,200 or they wouldn't unload. I had no choice but to pay. This is extortion.",
    user: mockUsers[3],
    company_name: "Two Men and a Truck",
    company_slug: "two-men-and-a-truck",
    category: "Moving Companies",
    state: "Florida",
    city: "Miami",
    severity: 5,
    status: "resolved",
    upvotes: 2341,
    downvotes: 67,
    comment_count: 412,
    view_count: 34521,
    created_at: "2026-03-01T11:20:00Z",
    is_featured: true,
  },
  {
    id: "complaint-5",
    title: "Contractor took $15,000 deposit and disappeared",
    content: "Hired ABC Renovations to remodel my kitchen. Gave them $15,000 as a deposit. They did some demo work and then stopped showing up. Won't return calls or texts. Found out they've done this to at least 5 other homeowners in our area.",
    user: mockUsers[4],
    company_name: "ABC Renovations",
    company_slug: "abc-renovations",
    category: "Contractors",
    state: "Illinois",
    city: "Chicago",
    severity: 5,
    status: "investigating",
    upvotes: 1876,
    downvotes: 23,
    comment_count: 267,
    view_count: 28934,
    created_at: "2026-03-05T08:30:00Z",
    is_featured: true,
  },
  {
    id: "complaint-6",
    title: "Real estate agent lied about flood zone to close the sale",
    content: "Our agent told us the property was NOT in a flood zone. First year, we got flooded and found out we're in Zone AE. Insurance is now $4,000/year extra. Agent refuses responsibility.",
    user: mockUsers[5],
    company_name: "Century 21 Realty",
    company_slug: "century-21-realty",
    category: "Real Estate",
    state: "Louisiana",
    city: "New Orleans",
    severity: 5,
    status: "open",
    upvotes: 934,
    downvotes: 19,
    comment_count: 145,
    view_count: 15678,
    created_at: "2026-03-06T13:00:00Z",
    is_featured: false,
  },
  {
    id: "complaint-7",
    title: "Property manager ignoring mold problem for 6 months",
    content: "I've reported black mold in our bathroom ceiling 12 times. They keep 'scheduling' maintenance that never shows up. My kids have developed respiratory issues. I have documentation of every request.",
    user: mockUsers[6],
    company_name: "Lincoln Property Company",
    company_slug: "lincoln-property-company",
    category: "Property Management",
    state: "Georgia",
    city: "Atlanta",
    severity: 5,
    status: "open",
    upvotes: 1567,
    downvotes: 11,
    comment_count: 203,
    view_count: 21345,
    created_at: "2026-03-04T10:15:00Z",
    is_featured: true,
  },
  {
    id: "complaint-8",
    title: "HOA president using funds for personal expenses",
    content: "I obtained HOA financial records through a formal request. The HOA president has been using community funds for personal vacations, dinners, and even a new TV. Over $23,000 in the past year alone.",
    user: mockUsers[7],
    company_name: "Sunset Valley Homeowners Association",
    company_slug: "sunset-valley-hoa",
    category: "HOA",
    state: "Arizona",
    city: "Phoenix",
    severity: 5,
    status: "investigating",
    upvotes: 3456,
    downvotes: 89,
    comment_count: 567,
    view_count: 45678,
    created_at: "2026-03-02T14:45:00Z",
    is_featured: true,
  },
  // Mobile, Alabama Complaints
  {
    id: "complaint-9",
    title: "Maddox Properties kept my $1,200 security deposit with fake charges",
    content: "Lived at Oak Tree Apartments managed by Maddox Properties for 2 years. Left the apartment spotless with photo documentation. They kept my entire deposit claiming damage that did not exist. This is theft!",
    user: mockUsers[8],
    company_name: "Maddox Properties LLC",
    company_slug: "maddox-properties-llc",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 234,
    downvotes: 5,
    comment_count: 67,
    view_count: 4521,
    created_at: "2026-03-14T09:30:00Z",
    is_featured: true,
  },
  {
    id: "complaint-10",
    title: "Black mold at Plantation Apartments making my family sick",
    content: "Reported black mold in our unit at Plantation Apartments 4 months ago. They sent someone who painted over it. Now my kids have breathing problems. This is a health hazard and they refuse to properly remediate.",
    user: mockUsers[9],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 189,
    downvotes: 3,
    comment_count: 45,
    view_count: 3234,
    created_at: "2026-03-10T14:15:00Z",
    is_featured: true,
  },
  {
    id: "complaint-11",
    title: "Oak Tree Apartments security gate broken for 6 months - cars being broken into",
    content: "The security gate at Oak Tree Apartments has been broken since October. My car and my neighbor's cars have been broken into multiple times. Management says they're 'working on it' but nothing happens. We pay for secure parking!",
    user: mockUsers[0],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 1567,
    downvotes: 12,
    comment_count: 238,
    view_count: 28760,
    created_at: "2026-03-08T11:45:00Z",
    is_featured: true,
  },
  // ELECTRICAL ISSUES
  {
    id: "complaint-12",
    title: "Plantation Apartments electrical fire hazard - exposed wires everywhere",
    content: "Unit 204 at Plantation Apartments has exposed electrical wires in the kitchen and bathroom. Reported to management 8 times over 5 months. They sent an unlicensed handyman who taped over the wires with electrical tape. Fire marshal needs to inspect this death trap.",
    user: mockUsers[1],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 2341,
    downvotes: 8,
    comment_count: 412,
    view_count: 34521,
    created_at: "2026-03-12T08:30:00Z",
    is_featured: true,
  },
  {
    id: "complaint-13",
    title: "Oak Tree electrical panel sparking - management ignoring emergency",
    content: "The main electrical panel in my unit is literally sparking when you turn on the AC. Called emergency maintenance 3 times. They said 'we'll get to it.' This could burn the whole building down. I have video evidence.",
    user: mockUsers[2],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 1876,
    downvotes: 5,
    comment_count: 289,
    view_count: 41234,
    created_at: "2026-03-11T14:20:00Z",
    is_featured: true,
  },
  // PLUMBING DISASTERS
  {
    id: "complaint-14",
    title: "Raw sewage backing up into Plantation Apartments units for WEEKS",
    content: "Building C at Plantation Apartments has had raw sewage backing up into ground floor units for 3 weeks. The smell is unbearable. Children are getting sick. Management says the plumber is 'scheduled' but no one ever comes. This is a public health emergency!",
    user: mockUsers[3],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 3456,
    downvotes: 11,
    comment_count: 567,
    view_count: 52341,
    created_at: "2026-03-09T09:15:00Z",
    is_featured: true,
  },
  {
    id: "complaint-15",
    title: "Oak Tree Apartments flooded my unit - destroyed everything I own",
    content: "Upstairs neighbor's toilet overflowed due to building plumbing issues. Management knew about the plumbing problems for months. My entire apartment flooded. Lost furniture, electronics, clothes - over $15,000 in damage. They're refusing to compensate or even fix the plumbing.",
    user: mockUsers[4],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 2134,
    downvotes: 7,
    comment_count: 345,
    view_count: 38976,
    created_at: "2026-03-07T16:45:00Z",
    is_featured: true,
  },
  // NOT PAYING CONTRACTORS / SMALL BUSINESSES
  {
    id: "complaint-16",
    title: "Maddox Properties owes my plumbing company $47,000 - REFUSING TO PAY",
    content: "I own Mobile Plumbing Solutions. Did emergency plumbing work at 6 Maddox properties over 4 months. They keep 'losing' invoices and making excuses. $47,000 outstanding. Other contractors in Mobile have the same story. They USE small businesses then don't pay!",
    user: mockUsers[5],
    company_name: "Maddox Properties LLC",
    company_slug: "maddox-properties-llc",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 4521,
    downvotes: 23,
    comment_count: 678,
    view_count: 67834,
    created_at: "2026-03-13T10:30:00Z",
    is_featured: true,
  },
  {
    id: "complaint-17",
    title: "Plantation Apartments stiffed my electrical company for $23,500",
    content: "Gulf Coast Electric here. Rewired 3 buildings at Plantation Apartments. Completed work in January. It's now March and they've paid NOTHING. Won't return calls. Lawyer letters ignored. This is destroying my small business. WARNING TO ALL CONTRACTORS!",
    user: mockUsers[6],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 3876,
    downvotes: 15,
    comment_count: 534,
    view_count: 54321,
    created_at: "2026-03-12T11:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-18",
    title: "Oak Tree Apartments refuses to pay HVAC contractor - $31,000 owed",
    content: "Alabama Comfort HVAC. Installed 12 new AC units at Oak Tree. Work completed, inspected, approved. Payment? 'The check is in the mail' for 4 months now. My employees need their paychecks. These people are CROOKS who prey on local businesses!",
    user: mockUsers[7],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 2987,
    downvotes: 9,
    comment_count: 423,
    view_count: 45678,
    created_at: "2026-03-10T15:20:00Z",
    is_featured: true,
  },
  // PEST INFESTATIONS
  {
    id: "complaint-19",
    title: "Roach infestation so bad at Plantation I found them in my REFRIGERATOR",
    content: "I've lived in some rough places but Plantation Apartments takes the cake. Roaches in the fridge, in the microwave, in my kids' beds. Reported monthly for a year. They send someone to spray water (I tested it - just water) and nothing changes. Health department needs to shut this place down.",
    user: mockUsers[8],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 4123,
    downvotes: 19,
    comment_count: 612,
    view_count: 71234,
    created_at: "2026-03-11T08:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-20",
    title: "Bedbugs spread to entire building at Oak Tree - management did NOTHING",
    content: "One unit got bedbugs and management refused to treat the building. Now the entire 3rd floor has them including my unit. They want ME to pay for treatment! $1,400 for something their negligence caused. Had to throw away my mattress and furniture.",
    user: mockUsers[9],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 2654,
    downvotes: 8,
    comment_count: 389,
    view_count: 38765,
    created_at: "2026-03-08T13:45:00Z",
    is_featured: true,
  },
  // SECURITY DEPOSIT THEFT
  {
    id: "complaint-21",
    title: "Maddox Properties kept $2,800 deposit - apartment was SPOTLESS",
    content: "Lived at Oak Tree (Maddox property) for 3 years. Never late on rent. Left the apartment cleaner than when I moved in. Professional cleaning receipt. Video walkthrough. They still kept my entire $2,800 deposit claiming 'damages' with no itemization. This is THEFT.",
    user: mockUsers[0],
    company_name: "Maddox Properties LLC",
    company_slug: "maddox-properties-llc",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 3234,
    downvotes: 12,
    comment_count: 478,
    view_count: 52341,
    created_at: "2026-03-14T09:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-22",
    title: "Plantation Apartments charging tenants for pre-existing damage",
    content: "Got my move-out statement. Being charged $1,200 for 'carpet damage' that was there when I moved in. I have photos dated from move-in day proving the stains existed. They lose all move-in inspection forms conveniently. Class action forming - DM me.",
    user: mockUsers[1],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 2876,
    downvotes: 11,
    comment_count: 401,
    view_count: 43210,
    created_at: "2026-03-13T14:30:00Z",
    is_featured: true,
  },
  // HARASSMENT & RETALIATION
  {
    id: "complaint-23",
    title: "Oak Tree management harassing me after I reported code violations",
    content: "After I called the health department about the mold, Oak Tree started citing me for BS violations. Trash can 'too close' to building. Car 'parked wrong.' They're trying to evict me in retaliation. This is illegal retaliation and I have a lawyer.",
    user: mockUsers[2],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 1987,
    downvotes: 6,
    comment_count: 312,
    view_count: 34567,
    created_at: "2026-03-12T16:00:00Z",
    is_featured: true,
  },
  // HEATING/COOLING FAILURES
  {
    id: "complaint-24",
    title: "No heat for 3 weeks in JANUARY at Plantation - elderly mother hospitalized",
    content: "Furnace broke January 5th. It's now January 26th and still no heat. My 78-year-old mother lives with me. She got pneumonia and was hospitalized for 6 days. Plantation refuses to provide space heaters or fix the problem. This almost killed her.",
    user: mockUsers[3],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 5234,
    downvotes: 14,
    comment_count: 723,
    view_count: 89123,
    created_at: "2026-01-26T10:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-25",
    title: "AC broken for entire summer at Oak Tree - 95+ degree apartment",
    content: "June through August with no AC in Mobile, Alabama. Temperatures inside hit 98 degrees. Multiple emergency calls ignored. They finally sent someone in SEPTEMBER who said the whole unit needs replacing. My electricity bill tripled from running fans 24/7.",
    user: mockUsers[4],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "resolved",
    upvotes: 3456,
    downvotes: 8,
    comment_count: 512,
    view_count: 67890,
    created_at: "2025-09-15T14:00:00Z",
    is_featured: true,
  },
  // WATER ISSUES
  {
    id: "complaint-26",
    title: "Brown water coming out of faucets at Plantation for MONTHS",
    content: "The water at Plantation Apartments looks like coffee. Children, pregnant women, everyone drinking this. Management says it's 'minerals' and 'safe.' Had it tested - high iron and unknown contaminants. They refuse to fix the pipes or provide bottled water.",
    user: mockUsers[5],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 4567,
    downvotes: 21,
    comment_count: 634,
    view_count: 78234,
    created_at: "2026-03-06T11:30:00Z",
    is_featured: true,
  },
  // MORE CONTRACTOR COMPLAINTS
  {
    id: "complaint-27",
    title: "Maddox Properties owes local painters $18,000 - 6 months overdue",
    content: "Southern Paint Pros here. Painted 40+ units for Maddox Properties at Plantation and Oak Tree. Completed August 2025. Not a single payment received. They keep saying 'accounting issues.' Meanwhile I had to lay off 2 employees. DO NOT WORK FOR THESE PEOPLE.",
    user: mockUsers[6],
    company_name: "Maddox Properties LLC",
    company_slug: "maddox-properties-llc",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 3123,
    downvotes: 10,
    comment_count: 456,
    view_count: 51234,
    created_at: "2026-02-28T09:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-28",
    title: "Landscaping company owed $12,500 by Oak Tree management",
    content: "Green Thumb Landscaping. Monthly contract for Oak Tree Apartments lawn care. Haven't been paid since October. That's 5 months of work - $12,500. When I stopped service they threatened to sue ME for breach of contract. Unbelievable.",
    user: mockUsers[7],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 2345,
    downvotes: 7,
    comment_count: 312,
    view_count: 34567,
    created_at: "2026-03-01T15:45:00Z",
    is_featured: true,
  },
  {
    id: "complaint-29",
    title: "Roofing company $67,000 in the hole after Plantation job",
    content: "Mobile Roofing Solutions. Major roof repair project at Plantation. 3 buildings. Materials alone were $45,000 out of pocket. Labor, equipment, insurance - total $67,000. They approved everything, signed off on completion, and then... nothing. Ghost. My company may not survive this.",
    user: mockUsers[8],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 5678,
    downvotes: 25,
    comment_count: 823,
    view_count: 92341,
    created_at: "2026-03-14T08:00:00Z",
    is_featured: true,
  },
  // GENERAL SAFETY
  {
    id: "complaint-30",
    title: "Staircase collapsed at Oak Tree injuring 2 residents",
    content: "The metal staircase on Building B partially collapsed last Tuesday. Two residents injured, one seriously. We've been complaining about those rusty stairs for YEARS. Management did nothing. Now someone almost died. Lawyer contacted, lawsuit incoming.",
    user: mockUsers[9],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 6234,
    downvotes: 18,
    comment_count: 934,
    view_count: 112345,
    created_at: "2026-03-15T06:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-31",
    title: "Plantation fire alarms haven't worked in 2 YEARS",
    content: "Had a small kitchen fire last week. Guess what didn't go off? The smoke detectors. Because they haven't worked in 2 years despite constant reports. We could have all died. Fire marshal has been notified. This place is a death trap.",
    user: mockUsers[0],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 4876,
    downvotes: 13,
    comment_count: 678,
    view_count: 78901,
    created_at: "2026-03-14T22:00:00Z",
    is_featured: true,
  },
  // LEASE VIOLATIONS BY MANAGEMENT
  {
    id: "complaint-32",
    title: "Oak Tree raised rent 40% mid-lease - ILLEGAL",
    content: "Signed a 12-month lease at $850/month. 6 months in they sent a letter demanding $1,190/month or eviction. That's a 40% increase MID-LEASE. This is completely illegal. They're betting tenants don't know their rights.",
    user: mockUsers[1],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 3456,
    downvotes: 9,
    comment_count: 489,
    view_count: 56789,
    created_at: "2026-03-10T12:00:00Z",
    is_featured: true,
  },
  // DISCRIMINATION
  {
    id: "complaint-33",
    title: "Plantation Apartments denying applications based on where people work",
    content: "Applied to Plantation with perfect credit, good income, references. Denied because I work at a 'nightclub' (I'm a bartender at a restaurant with a bar). This is employment discrimination. Filing with HUD and Fair Housing.",
    user: mockUsers[2],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 4,
    status: "investigating",
    upvotes: 2134,
    downvotes: 156,
    comment_count: 312,
    view_count: 34567,
    created_at: "2026-03-09T14:00:00Z",
    is_featured: false,
  },
  // LOCKOUTS
  {
    id: "complaint-34",
    title: "Maddox illegally locked me out over $50 late fee dispute",
    content: "Rent was paid. They claim I owe a $50 late fee from 8 months ago (I don't). Without any notice or court order, they changed my locks. My belongings, my medications, my pets - all inside. Had to call police. This is ILLEGAL self-help eviction.",
    user: mockUsers[3],
    company_name: "Maddox Properties LLC",
    company_slug: "maddox-properties-llc",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 3789,
    downvotes: 11,
    comment_count: 534,
    view_count: 61234,
    created_at: "2026-03-13T18:00:00Z",
    is_featured: true,
  },
  // GENERAL CONTRACTORS
  {
    id: "complaint-35",
    title: "Security company owed $8,900 by Plantation - guards haven't been paid",
    content: "SecureGuard Services. Contract for overnight security at Plantation. My guards are quitting because Plantation hasn't paid US so I can't pay THEM. $8,900 outstanding. Property now has no security because of their nonpayment.",
    user: mockUsers[4],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 4,
    status: "open",
    upvotes: 1876,
    downvotes: 5,
    comment_count: 267,
    view_count: 28901,
    created_at: "2026-03-11T10:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-36",
    title: "Appliance repair company warns: Maddox Properties doesn't pay",
    content: "ApplianceFix Mobile. Just adding to the pile. Replaced refrigerators and stoves across multiple Maddox properties. Invoice: $14,200. Payment: $0. It's been 4 months. Fellow contractors - DEMAND PAYMENT UPFRONT or don't work for them!",
    user: mockUsers[5],
    company_name: "Maddox Properties LLC",
    company_slug: "maddox-properties-llc",
    category: "Contractors",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "open",
    upvotes: 2567,
    downvotes: 8,
    comment_count: 345,
    view_count: 41234,
    created_at: "2026-03-12T13:00:00Z",
    is_featured: true,
  },
  // MOLD ISSUES
  {
    id: "complaint-37",
    title: "Oak Tree mold so bad the walls are turning BLACK",
    content: "Posted photos in comments. The walls in my bathroom and closet are literally BLACK with mold. Kids have chronic respiratory issues now. Doctor confirmed it's environmental. Oak Tree's solution? Paint over it. We need a class action.",
    user: mockUsers[6],
    company_name: "Oak Tree Apartments",
    company_slug: "oak-tree-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 4321,
    downvotes: 14,
    comment_count: 612,
    view_count: 73456,
    created_at: "2026-03-07T09:00:00Z",
    is_featured: true,
  },
  {
    id: "complaint-38",
    title: "Toxic mold at Plantation put my baby in the hospital",
    content: "My 8-month-old was hospitalized with severe respiratory distress. Doctors found mold spores in her lungs. The source? Our Plantation Apartments unit. I have medical records, mold test results, everything. They're going to pay for this.",
    user: mockUsers[7],
    company_name: "Plantation Apartments",
    company_slug: "plantation-apartments-mobile",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    severity: 5,
    status: "investigating",
    upvotes: 7234,
    downvotes: 22,
    comment_count: 1023,
    view_count: 134567,
    created_at: "2026-03-15T07:00:00Z",
    is_featured: true,
  },
];

// Mock discussions
export const mockDiscussions = [
  {
    id: "discussion-1",
    title: "Anyone else having issues with Greystar's maintenance portal?",
    content: "Their online maintenance request system has been down for 2 weeks. Can't submit any requests. Phone wait times are 45+ minutes.",
    user: mockUsers[8],
    company_name: "Greystar Property Management",
    company_slug: "greystar-property-management",
    upvotes: 234,
    downvotes: 5,
    comment_count: 67,
    created_at: "2026-03-09T08:30:00Z",
  },
  {
    id: "discussion-2",
    title: "Class action lawsuit forming against Riverside Heights HOA",
    content: "A group of us are consulting with an attorney about the excessive fines and selective enforcement. If you've been affected, reach out.",
    user: mockUsers[9],
    company_name: "Riverside Heights HOA",
    company_slug: "riverside-heights-hoa",
    upvotes: 567,
    downvotes: 34,
    comment_count: 189,
    created_at: "2026-03-08T16:20:00Z",
  },
];

// Mock comments
export const mockComments = [
  {
    id: "comment-1",
    content: "This happened to me too! Same property management company. They kept $1,800 of my deposit claiming 'carpet replacement' when I only lived there 8 months.",
    user: mockUsers[7],
    upvotes: 145,
    downvotes: 2,
    created_at: "2026-03-08T15:45:00Z",
  },
  {
    id: "comment-2",
    content: "Document everything and file a complaint with your state's Department of Consumer Affairs. That's what finally got them to respond to me.",
    user: mockUsers[9],
    upvotes: 234,
    downvotes: 1,
    created_at: "2026-03-08T16:12:00Z",
  },
  {
    id: "comment-3",
    content: "I'm a tenant rights attorney. This is a clear violation of California Civil Code 1950.5. You're entitled to the full deposit plus statutory damages. DM me if you need help.",
    user: mockUsers[1],
    upvotes: 456,
    downvotes: 3,
    created_at: "2026-03-08T17:30:00Z",
    is_verified: true,
  },
  // Comments for Mobile AL properties
  {
    id: "comment-4",
    content: "I'm a contractor in Mobile. Oak Tree and Plantation both owe me money too. We need to organize a meeting of all affected contractors. There's strength in numbers.",
    user: mockUsers[4],
    upvotes: 567,
    downvotes: 2,
    created_at: "2026-03-14T10:00:00Z",
  },
  {
    id: "comment-5",
    content: "Former maintenance worker at Plantation here. They told us to 'just paint over' any mold we found. I quit because I couldn't live with myself. Happy to provide testimony.",
    user: mockUsers[5],
    upvotes: 892,
    downvotes: 4,
    created_at: "2026-03-14T11:30:00Z",
    is_verified: false,
  },
  {
    id: "comment-6",
    content: "My electrician friend inspected Oak Tree's electrical panels. He said it's 'a matter of when, not if' there's a fire. Called the fire marshal. Everyone should do the same.",
    user: mockUsers[6],
    upvotes: 734,
    downvotes: 3,
    created_at: "2026-03-13T14:00:00Z",
  },
  {
    id: "comment-7",
    content: "Class action lawsuit forming against Maddox Properties. If you're owed money or had your deposit stolen, contact the Mobile County Bar Association. Multiple attorneys interested.",
    user: mockUsers[1],
    upvotes: 1234,
    downvotes: 8,
    created_at: "2026-03-15T09:00:00Z",
    is_verified: true,
  },
  {
    id: "comment-8",
    content: "I have photos of the raw sewage in Building C. Management tried to say it was 'just water.' It's literally feces and toilet paper. How is this place still operating?",
    user: mockUsers[8],
    upvotes: 678,
    downvotes: 2,
    created_at: "2026-03-10T16:00:00Z",
  },
  {
    id: "comment-9",
    content: "Worked security at Plantation for 3 months before they stopped paying. The conditions inside are worse than what's being reported. Management threatened us not to talk.",
    user: mockUsers[9],
    upvotes: 543,
    downvotes: 1,
    created_at: "2026-03-12T08:00:00Z",
  },
  {
    id: "comment-10",
    content: "Alabama Department of Public Health needs to inspect BOTH properties. I'm organizing a group call to their complaint line tomorrow at 9am. Join us - strength in numbers!",
    user: mockUsers[0],
    upvotes: 456,
    downvotes: 2,
    created_at: "2026-03-14T20:00:00Z",
  },
  {
    id: "comment-11",
    content: "News tip: Local TV station WKRG is doing an investigation into slumlords in Mobile. They want to hear from affected tenants. Call their tip line!",
    user: mockUsers[2],
    upvotes: 892,
    downvotes: 5,
    created_at: "2026-03-15T07:30:00Z",
  },
  {
    id: "comment-12",
    content: "I'm keeping a spreadsheet of every contractor who's been stiffed by Maddox/Plantation/Oak Tree. So far I have 23 businesses totaling over $340,000 owed. DM me to add yours.",
    user: mockUsers[3],
    upvotes: 1567,
    downvotes: 7,
    created_at: "2026-03-14T15:00:00Z",
  },
];

// Mock activity feed items
export const mockActivityFeed = [
  {
    id: "activity-0a",
    type: "complaint",
    message: "filed a complaint against",
    user: mockUsers[8],
    company_name: "Maddox Properties LLC",
    created_at: "2026-03-10T09:50:00Z",
  },
  {
    id: "activity-0b",
    type: "evidence_uploaded",
    message: "uploaded mold photos for complaint against",
    user: mockUsers[9],
    company_name: "Plantation Apartments",
    created_at: "2026-03-10T09:48:00Z",
  },
  {
    id: "activity-0c",
    type: "comment",
    message: "commented on a complaint about",
    user: mockUsers[0],
    company_name: "Oak Tree Apartments",
    created_at: "2026-03-10T09:47:00Z",
  },
  {
    id: "activity-1",
    type: "complaint",
    message: "filed a complaint against",
    user: mockUsers[0],
    company_name: "Greystar Property Management",
    created_at: "2026-03-10T09:45:00Z",
  },
  {
    id: "activity-2",
    type: "comment",
    message: "commented on a complaint about",
    user: mockUsers[7],
    company_name: "Lincoln Property Company",
    created_at: "2026-03-10T09:42:00Z",
  },
  {
    id: "activity-3",
    type: "vote",
    message: "upvoted a complaint against",
    user: mockUsers[3],
    company_name: "Two Men and a Truck",
    created_at: "2026-03-10T09:40:00Z",
  },
  {
    id: "activity-4",
    type: "discussion",
    message: "started a discussion about",
    user: mockUsers[8],
    company_name: "Riverside Heights HOA",
    created_at: "2026-03-10T09:38:00Z",
  },
  {
    id: "activity-5",
    type: "user_joined",
    message: "joined BadBizExposed",
    user: mockUsers[5],
    created_at: "2026-03-10T09:35:00Z",
  },
  {
    id: "activity-6",
    type: "evidence_uploaded",
    message: "uploaded evidence for complaint against",
    user: mockUsers[4],
    company_name: "ABC Renovations",
    created_at: "2026-03-10T09:33:00Z",
  },
  {
    id: "activity-7",
    type: "complaint",
    message: "filed a complaint against",
    user: mockUsers[2],
    company_name: "John Michaels Properties",
    created_at: "2026-03-10T09:30:00Z",
  },
  {
    id: "activity-8",
    type: "comment",
    message: "replied to a discussion about",
    user: mockUsers[9],
    company_name: "Century 21 Realty",
    created_at: "2026-03-10T09:28:00Z",
  },
];

// Mock companies
export const mockCompanies = [
  {
    id: "company-1",
    name: "Greystar Property Management",
    slug: "greystar-property-management",
    description: "One of the largest property management companies in the United States",
    category: "Property Management",
    state: "California",
    city: "Los Angeles",
    complaint_count: 847,
    discussion_count: 234,
    avg_rating: 1.8,
    is_verified: true,
  },
  {
    id: "company-2",
    name: "Riverside Heights HOA",
    slug: "riverside-heights-hoa",
    description: "Homeowners association in Austin, Texas",
    category: "HOA",
    state: "Texas",
    city: "Austin",
    complaint_count: 423,
    discussion_count: 156,
    avg_rating: 1.2,
    is_verified: false,
  },
  {
    id: "company-3",
    name: "Lincoln Property Company",
    slug: "lincoln-property-company",
    description: "National property management and real estate firm",
    category: "Property Management",
    state: "Georgia",
    city: "Atlanta",
    complaint_count: 612,
    discussion_count: 189,
    avg_rating: 2.1,
    is_verified: true,
  },
  {
    id: "company-4",
    name: "Two Men and a Truck",
    slug: "two-men-and-a-truck",
    description: "National moving company franchise",
    category: "Moving Companies",
    state: "Florida",
    city: "Miami",
    complaint_count: 534,
    discussion_count: 98,
    avg_rating: 2.4,
    is_verified: true,
  },
  {
    id: "company-5",
    name: "ABC Renovations",
    slug: "abc-renovations",
    description: "Home renovation contractor in Chicago area",
    category: "Contractors",
    state: "Illinois",
    city: "Chicago",
    complaint_count: 267,
    discussion_count: 45,
    avg_rating: 1.1,
    is_verified: false,
  },
  {
    id: "company-6",
    name: "Sunset Valley HOA",
    slug: "sunset-valley-hoa",
    description: "Homeowners association in Phoenix, Arizona",
    category: "HOA",
    state: "Arizona",
    city: "Phoenix",
    complaint_count: 389,
    discussion_count: 112,
    avg_rating: 1.4,
    is_verified: false,
  },
  // Mobile, Alabama Properties - Priority Tracking
  {
    id: "company-7",
    name: "Oak Tree Apartments",
    slug: "oak-tree-apartments-mobile",
    description: "Apartment complex in Mobile, Alabama with thousands of complaints about maintenance failures, pest infestations, electrical hazards, and refusal to return security deposits",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    complaint_count: 2847,
    discussion_count: 534,
    avg_rating: 1.2,
    is_verified: false,
    is_priority_tracking: true,
  },
  {
    id: "company-8",
    name: "Plantation Apartments",
    slug: "plantation-apartments-mobile",
    description: "Notorious Mobile, Alabama property with massive complaint volume for black mold, plumbing disasters, not paying contractors, and tenant harassment",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    complaint_count: 3156,
    discussion_count: 612,
    avg_rating: 1.1,
    is_verified: false,
    is_priority_tracking: true,
  },
  {
    id: "company-9",
    name: "Maddox Properties LLC",
    slug: "maddox-properties-llc",
    description: "Property management company in Mobile, Alabama with pattern of security deposit theft, contractor nonpayment, and code violations",
    category: "Property Management",
    state: "Alabama",
    city: "Mobile",
    complaint_count: 1834,
    discussion_count: 367,
    avg_rating: 1.0,
    is_verified: false,
    is_priority_tracking: true,
  },
];

// Mock scandals/breaking news
export const mockScandals = [
  {
    id: "scandal-1",
    title: "BREAKING: Greystar executives caught on tape discussing deposit retention quotas",
    summary: "Leaked internal memo reveals company policy to retain at least 40% of security deposits",
    company_name: "Greystar Property Management",
    severity: 5,
    source_url: "#",
    created_at: "2026-03-10T06:00:00Z",
  },
  {
    id: "scandal-2",
    title: "HOA President indicted on embezzlement charges",
    summary: "FBI investigation uncovers $450,000 missing from community funds",
    company_name: "Sunset Valley HOA",
    severity: 5,
    source_url: "#",
    created_at: "2026-03-09T14:30:00Z",
  },
];

// Review tracking data for priority properties
export const mockReviews = [
  {
    id: "review-1",
    company_id: "company-7",
    company_name: "Oak Tree Apartments",
    review_source: "Google",
    review_date: "2026-03-15",
    reviewer_name: "Anonymous Tenant",
    star_rating: 1,
    review_type: "Complaint",
    complaint_categories: ["Maintenance Issues", "Pest Problems"],
    full_review_text: "Roaches everywhere. Reported multiple times but management does nothing. The apartment had visible mold in the bathroom when I moved in and they just painted over it.",
    severity_level: "Critical",
    repeat_issue_flag: true,
    legal_risk_flag: true,
    notes: "Health hazard - potential legal action",
  },
  {
    id: "review-2",
    company_id: "company-7",
    company_name: "Oak Tree Apartments",
    review_source: "Apartments.com",
    review_date: "2026-03-10",
    reviewer_name: "Former Resident",
    star_rating: 1,
    review_type: "Negative",
    complaint_categories: ["Safety/Crime Concerns", "Property Condition"],
    full_review_text: "Security gate has been broken for 6 months. Multiple car break-ins in the parking lot. Management refuses to fix it or install cameras.",
    severity_level: "High",
    repeat_issue_flag: true,
    legal_risk_flag: false,
    notes: "Safety concern - repeated complaints",
  },
  {
    id: "review-3",
    company_id: "company-8",
    company_name: "Plantation Apartments",
    review_source: "Yelp",
    review_date: "2026-03-12",
    reviewer_name: "J. Williams",
    star_rating: 1,
    review_type: "Complaint",
    complaint_categories: ["Billing/Hidden Fees", "Staff/Management Behavior"],
    full_review_text: "They charged me $500 in 'cleaning fees' when I moved out even though I left it spotless. Office staff is rude and unhelpful. Avoid at all costs!",
    severity_level: "High",
    repeat_issue_flag: true,
    legal_risk_flag: true,
    notes: "Potential security deposit violation",
  },
  {
    id: "review-4",
    company_id: "company-8",
    company_name: "Plantation Apartments",
    review_source: "Google",
    review_date: "2026-03-08",
    reviewer_name: "Mobile Resident",
    star_rating: 2,
    review_type: "Negative",
    complaint_categories: ["Noise/Neighbors", "Staff/Management Behavior"],
    full_review_text: "Constant noise issues with upstairs neighbors. Filed multiple complaints but management says there's nothing they can do. Thin walls, no peace.",
    severity_level: "Moderate",
    repeat_issue_flag: false,
    legal_risk_flag: false,
    notes: "",
  },
  {
    id: "review-5",
    company_id: "company-9",
    company_name: "Maddox Properties LLC",
    review_source: "BBB",
    review_date: "2026-03-14",
    reviewer_name: "T. Johnson",
    star_rating: 1,
    review_type: "Complaint",
    complaint_categories: ["Lease/Contract Issues", "Billing/Hidden Fees"],
    full_review_text: "Maddox Properties refused to return my security deposit despite the apartment being in perfect condition. They made up charges that did not exist. This company preys on tenants.",
    severity_level: "Critical",
    repeat_issue_flag: true,
    legal_risk_flag: true,
    notes: "Pattern of deposit retention - legal risk",
  },
  {
    id: "review-6",
    company_id: "company-9",
    company_name: "Maddox Properties LLC",
    review_source: "Google",
    review_date: "2026-03-05",
    reviewer_name: "Frustrated Renter",
    star_rating: 1,
    review_type: "Complaint",
    complaint_categories: ["Maintenance Issues", "Property Condition", "Pest Problems"],
    full_review_text: "Water damage in ceiling went unrepaired for 3 months. Now there's black mold. They sent someone out who just painted over it. My kids have been getting sick. This is a health hazard!",
    severity_level: "Critical",
    repeat_issue_flag: true,
    legal_risk_flag: true,
    notes: "Health hazard - child safety concern - immediate action needed",
  },
  {
    id: "review-7",
    company_id: "company-9",
    company_name: "Maddox Properties LLC",
    review_source: "Apartments.com",
    review_date: "2026-02-28",
    reviewer_name: "S. Davis",
    star_rating: 1,
    review_type: "Negative",
    complaint_categories: ["Staff/Management Behavior", "Lease/Contract Issues"],
    full_review_text: "Management is impossible to reach. They changed the lease terms mid-lease and tried to charge us more rent. When we complained, they threatened eviction.",
    severity_level: "High",
    repeat_issue_flag: false,
    legal_risk_flag: true,
    notes: "Potential lease violation",
  },
];

// Complaint categories for review tracking
export const complaintCategories = [
  "Maintenance Issues",
  "Pest Problems",
  "Safety/Crime Concerns",
  "Staff/Management Behavior",
  "Billing/Hidden Fees",
  "Property Condition",
  "Noise/Neighbors",
  "Lease/Contract Issues",
];

// Review sources
export const reviewSources = [
  "Google",
  "Yelp",
  "Apartments.com",
  "Facebook",
  "BBB",
  "Zillow",
  "ConsumerAffairs",
  "TrustPilot",
  "Other",
];

// Severity levels
export const severityLevels = ["Low", "Moderate", "High", "Critical"];

// Helper function to get random user
export function getRandomUser() {
  return mockUsers[Math.floor(Math.random() * mockUsers.length)];
}

// Helper to format relative time
export function formatRelativeTime(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000);
  
  if (diffInSeconds < 60) return "just now";
  if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)}m ago`;
  if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)}h ago`;
  if (diffInSeconds < 604800) return `${Math.floor(diffInSeconds / 86400)}d ago`;
  return date.toLocaleDateString();
}
